site_name: AutoDLA
repo_url: https://github.com/GuzhiRegem/autoDLA
repo_name: autoDLA
edit_uri: edit/main/docs/


theme:
  name: material
  language: en
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  logo: assets/autodla-logo-simple.png
  favicon: assets/autodla-icon.png
plugins:
  - glightbox
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Introduction:
      - Overview: index.md
      - Installation: installation.md
      - Basic Usage: basic_usage.md
      - More Features: advanced_usage.md
      - AutoDLA WEB: autodla_web.md
      - Licence: license.md
  - Reference:
      - Dependencies: reference/dependencies_list.md
      - Environment variables: reference/environment_variables.md
      - Object: reference/object.md
      - Primary key: reference/primary_key.md