site_name: AutoDLA
repo_url: https://github.com/GuzhiRegem/autoDLA
repo_name: autoDLA
edit_uri: edit/main/docs/
theme:
  name: material
  language: en
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Introduction:
      - Overview: index.md
      - Installation: installation.md
      - Basic Usage: basic_usage.md
      - More Features: advanced_usage.md
      - AutoDLA WEB: autodla_web.md
  - Reference:
      - Dependencies: reference/dependencies_list.md
      - Object: reference/object.md
      - Primary key: reference/primary_key.md